version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - taskmanager

  backend:
    build: ./backend
    container_name: taskmanager_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/taskDB?authSource=admin  
    networks:
      - taskmanager

  frontend:
    build: ./testapp
    container_name: taskmanager_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    stdin_open: true
    tty: true
    networks:
      - taskmanager

networks:
  taskmanager:
    driver: bridge
